### ISSUE TITLE
Failed to activate the atom-typescript-zh-backticks package

### ISSUE THREAD

**Issue by noncreativetype** [ZombieHippie/atom-typescript-zh-backticks#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript-zh-backticks](https://github.com/ZombieHippie/atom-typescript-zh-backticks) package, v8.8.2-2

### Stack Trace

Failed to activate the atom-typescript-zh-backticks package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'ts-view'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'ts-view'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (C:\Users\kaptn\.atom\packages\atom-typescript-zh-backticks\dist\main\atom\components\ts-view.js:32:10)
    at Module._compile (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\kaptn\.atom\packages\atom-typescript-zh-backticks\dist\main\atom\components\componentRegistry.js:5:10)
    at Module._compile (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\kaptn\.atom\packages\atom-typescript-zh-backticks\dist\main\atom\commands\commands.js:29:10)
    at Module._compile (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\kaptn\.atom\packages\atom-typescript-zh-backticks\dist\main\atomts.js:11:16)
    at Module._compile (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\kaptn\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:715:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets-atom, v0.6.0
atom-typescript, v8.8.1
atom-typescript-zh-backticks, v8.8.2-2
autocomplete-ionic2-framework, v0.3.2
color-picker, v2.1.1
linter, v1.11.4

# Dev
No dev packages
```

**Comment by ZombieHippie** [comment]
Sorry, this package was not designed to run alongside atom-typescript as it is a fork of Atom TypeScript.

**Comment by ZombieHippie** [comment]
I'll look into just providing the grammars instead of everything together.

**Comment by shailu2006** [comment]
Thank you Zombie !
